<?php
/**
 * @file
 * Code for the Media feature.
 */

include_once('openpublish_media.features.inc');


/**
 * Implements hook_form_FORM_ID_alter()
 * 
 * Disable WYSIWYG on this field
 */
function openpublish_media_form_openpublish_video_node_form_alter(&$form, &$form_state, $form_id) {
  if (module_exists('wysiwyg') && isset($form['field_op_video_embed_code'])) {
    $lang = $form['field_op_video_embed_code']['#language'];
    $form['field_op_video_embed_code'][$lang][0]['#wysiwyg'] = FALSE;
  }
} 

/**
 *  Implementation of hook_preprocess_entity
 *  Add the caption as the title for each image
 */
function openpublish_media_preprocess_field(&$vars) {
  if ($vars['element']['#field_name'] == 'field_op_gallery_image') {
    foreach ($vars['element']['#items'] as $index => $item) {
      $entity = &$vars['items'][$index]['entity']['field_collection_item'][$item['value']];
      
      $title = $entity['field_op_gallery_image_caption'][0]['#markup'];
      $entity['field_op_gallery_image_image'][0]['#item']['title'] = $title;
    }
  }
}

function openpublish_media_preprocess_html(&$vars) {
  drupal_add_js(libraries_get_path('photoswipe') . '/lib/klass.min.js', array('group' => -101, 'weight' => 0));
  drupal_add_js(libraries_get_path('photoswipe') . '/code.photoswipe.jquery-3.0.5.min.js');
  drupal_add_js(drupal_get_path('module', 'openpublish_media') . '/js/photo-gallery.js');
  drupal_add_css(libraries_get_path('photoswipe') . '/photoswipe.css');
}

/**
 * Implementation of hook_js_alter
 * Upgrade jQuery to 1.7.2 but only on photo gallery pages
 */
function openpublish_media_js_alter(&$js) {
  $object = menu_get_object();
  if (!isset($object) || $object->type != 'openpublish_photo_gallery') {
    return;
  }
  $path = libraries_get_path('jquery-1.7') . '/jquery-1.7.2.min.js';
  if (!empty($path) && isset($js['misc/jquery.js'])) {
    // Copy the current jQuery file settings and change
    $js[$path] = $js['misc/jquery.js'];

    // Update necessary settings
    $js[$path]['version'] = 1.7;
    $js[$path]['data'] = $path;

    // Finally remove the original jQuery
    unset($js['misc/jquery.js']);
  }
}