<?php
/**
 * @file
 * Code for the Taxonomy_search_list feature.
 */

include_once('openpublish_advanced_taxonomy.features.inc');


function openpublish_advanced_taxonomy_form_taxonomy_form_vocabulary_alter(&$form, &$form_state) {
  
  $vocab_name = $form['#vocabulary']->machine_name;
  $options = array(0=>'Do not Use Advanced Search Page');
  foreach(field_info_fields() as $field) {
    if (($field['type'] == 'taxonomy_term_reference')) {
      foreach($field['settings']['allowed_values'] as $voc) {
        if ($voc['vocabulary'] = $vocab_name) {
         $options[$field['field_name']] = $field['field_name'];
          
        }
      }
    }
  };
  $key = "openpublish_advanced_taxonomy_field_$vocab_name";
  $form[$key] = array(
    '#type' => 'radios',
    '#title' => 'Field to Be used in Advance Taxonomy Page',
    '#options' => $options,
    '#default_value' => variable_get($key, 0),
  );
  $form['#submit'][] = 'openpublish_advanced_taxonomy_form_taxonomy_form_vocabulary_submit';
  
  //debug($form);
}
function openpublish_advanced_taxonomy_form_taxonomy_form_vocabulary_submit($form, &$form_state) {
  $vocab_name = $form['#vocabulary']->machine_name;
  $key = "openpublish_advanced_taxonomy_field_$vocab_name";
  variable_set($key, $form_state['values'][$key]);

  // If there is no taxonomy_view mode set then lets set it to full
  if($form_state['values'][$key] && ! $form_state['values']["taxonomy_view_$vocab_name"]) {
    variable_set("taxonomy_view_$vocab_name", 'full');
    $form_state['values']["taxonomy_view_$vocab_name"] = 'full';
  }
  
}

function openpublish_advanced_taxonomy_taxonomy_term_title($term) {
  module_load_include('inc', 'taxonomy', 'taxonomy.pages');
  return taxonomy_term_title($term);
}


function openpublish_advanced_taxonomy_add_taxonomy_filter($field_name, $tid) {
  $arg['id'] = $field_name;
  $arg['table'] = 'search_api_index_openpublish_node_index';
  $arg['field'] = $field_name;
  $arg['value'] = $tid;
  return $arg;
   
}
function openpublish_advanced_taxonomy_views_pre_view(&$view, $display_id) {
/*
  if(
    ($view->name = 'openpublish_advanced_taxonomy') &&
    ($display_id = 'block_3') &&
    ($term = menu_get_object('taxonomy_term', 2)) && 
    ($field_name = variable_get("openpublish_advanced_taxonomy_field_{$term->vocabulary_machine_name}"))
    ) {
    $arg = openpublish_advanced_taxonomy_add_taxonomy_filter($field_name, $term->tid);
    $view->display[$display_id]->handler->options['filters'][$field_name] = $arg;
    $view->display['default']->handler->options['filters'][$field_name] = $arg;
  }
*/
}
